name: CI/CD
on: [push]

jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm run lint
          npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          now-org-id: ${{ secrets.ZEIT_NOW_ORG }}
          now-project-id: ${{ secrets.ZEIT_PROJECT_ID }}
          working-directory: ui